name: CI
on:
  pull_request:
    branches: [ main ]
jobs:
  builds-project:
    name: Build builds-project
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v3
     # Install NPM dependencies, cache them correctly
      # and run all Cypress tests

     - name: Cypress
       uses: cypress-io/github-action@v5 # use the explicit version number
       with:
         build: yarn run build
         start: yarn start

